// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxkmmzxnjcjnnakytuhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a21tenhuamNqbm5ha3l0dWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNjQ3ODIsImV4cCI6MjA4NTk0MDc4Mn0.Cdm2Nvsn87K9vCU2v9Ijum5WO3L8_E2RIgpbsPhsSjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});